### ISSUE TITLE
The homepage does not have any pre-prepared notebooks

### ISSUE THREAD

**Issue by jeremy-feng** [diegofcornejo/vercel-jupyter-lite#1]
I followed the deployment method on Vercel and successfully obtained the JupyterLite interface similar to yours (https://jupyter.vercel.app/lab/index.html). However, the homepage does not have any pre-prepared notebooks, and all files in the `content` folder disappear.

![image](https://github.com/diegofcornejo/vercel-jupyter-lite/assets/44312563/b3940680-920b-412d-a1a3-056de1daafdb)

I'm wondering if you know how to include the files in the `content` folder when deploying a website on Vercel?

I would appreciate any guidance on how to resolve this issue. Thank you.

**Comment by jeremy-feng** [comment]
This issue is solved here: https://github.com/jupyterlite/jupyterlite/issues/1288

**Comment by diegofcornejo** [comment]
> This issue is solved here: [jupyterlite/jupyterlite#1288](https://github.com/jupyterlite/jupyterlite/issues/1288)

Thank you for this, at some point while I was writing the guide I commented out the line of content and forgot to uncomment it.
